POST http://127.0.0.1:1010/api/v1/users/signup HTTP/1.1
content-type: application/json

{
   "user_first_name": "Nosa",
   "user_last_name": "Osagiede",
      "user_role": "admin",
   "user_email": "n.osagiede@nirsal.com",
   "user_password": "monkeyP@wz112",
   "user_password_confirm": "monkeyP@wz112"
}

###
POST http://127.0.0.1:1010/api/v1/users/signup HTTP/1.1
content-type: application/json

{
   "user_first_name": "Abdullahi",
   "user_last_name": "Abubakar",
   "user_role": "admin",
   "user_email": "a.abubakar@nirsal.com",
   "user_password": "mi$$fits@d&nSa",
   "user_password_confirm": "mi$$fits@d&nSa"
}

###
POST http://127.0.0.1:1010/api/v1/users/signup HTTP/1.1
content-type: application/json

{
   "user_first_name": "Public",
   "user_last_name": "User",
   "user_role": "user",
   "user_email": "user@public.com",
   "user_password": "dooksie$%#--",
   "user_password_confirm": "dooksie$%#--"
}

###
POST http://127.0.0.1:1010/api/v1/users/login HTTP/1.1
content-type: application/json

{
   "user_email": "ndukao@hotmail.com",
   "user_password": "dooksie$%#--"
}

###
GET http://127.0.0.1:1010/api/v1/users/admin/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZGJkMGM4YjIyN2VmMjlhYzVjMjVkOCIsImlhdCI6MTYyNTAyMzQxMiwiZXhwIjoxNjI1MDU5NDEyfQ.MPtbM2-NpCnFj4Zwlvh8P-tD9SU7YylRk-Xh0ohCeD0

###
POST http://127.0.0.1:1010/api/v1/users/forgotPassword HTTP/1.1

###
GET http://127.0.0.1:1010/dashboard/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDg3ZjQ1NzQ0MjczMTFmODYyY2ZlMCIsImlhdCI6MTYyNDk2MDg2MywiZXhwIjoxNjI0OTYwODY4fQ.UqL7xIW3_h4SprEFspUnAwCu_YubkcjTl8l9vomfMjw